### ISSUE TITLE
Kindly ask the validation of ghostmarket-nft.io

### ISSUE THREAD

**Issue by zhong3401** [OnBlockIO/ghostmarket-sdk-js#18]
Pretty sure the email is received, since there is no response things become clear. Deposits should be returned.

**Comment by alexmpa** [comment]
Please explain what you are talking about. Site that you mentioned is not our site, some scam site which we do not control.

**Comment by zhong3401** [comment]
Does it not concern the ghostmarket that there are scammers using your brand?

**Comment by zhong3401** [comment]
Besides the whole web3 is no difference to scams

**Comment by zhong3401** [comment]
Also the portfolio of ghostmarket.io and ghostmarket-nft.io are close. When no money can be earned through ghostmarket.io, it makes sense to start a close one? I never mentioned the ghostmarket-nft.io is a scam, but you validated it, calling it a scam.

**Comment by zhong3401** [comment]
A serious discussion is required.

**Comment by alexmpa** [comment]
I really don't follow. Somebody used our name for scam, that's what scammers do. They create thousands of sites using names of brands on a daily basis. Users should always be careful and use only sites they are absolutely certain about.
